title: Marie Ungar
url: "https://marieungar.com"
baseurl: "/researcher/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
 - name: "Writing"
   link: "writing"
 - name: "Contact"
   link: "contact"
